application: scribblepic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css/boo
  static_dir: static/bootstrap/css

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /js/boo
  static_dir: static/bootstrap/js

- url: /.*
  script: webserver.app

libraries:
- name: jinja2
  version: latest
